services:
  odoo-v18-db:
    image: postgres:16-alpine
    container_name: odoo-v18-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo123
    ports:
      - "5436:5432"
    volumes:
      - odoo-v18-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo-v18:
    image: odoo:18
    container_name: odoo-v18-server
    depends_on:
      odoo-v18-db:
        condition: service_healthy
    environment:
      HOST: odoo-v18-db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo123
    ports:
      - "8073:8069"
    volumes:
      - odoo-v18-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf

volumes:
  odoo-v18-db-data:
  odoo-v18-data:
